In [4]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [5]:
## 放大显示的字体
from IPython.display import HTML
HTML("""
<style>
/* —— JupyterLab 渲染后的 Markdown —— */
.jp-MarkdownCell .jp-RenderedHTMLCommon {
  font-size: 1.20em;          /* 整体放大 20% */
  line-height: 1.6;
}

/* 可选：调大标题层级（按需调） */
.jp-MarkdownCell h1 { font-size: 1.9em; }
.jp-MarkdownCell h2 { font-size: 1.6em; }
.jp-MarkdownCell h3 { font-size: 1.35em; }

/* 可选：渲染公式（MathJax v3）一起放大 */
.mjx-container { font-size: 115% !important; }
</style>
""")

In [8]:
import numpy as np
import matplotlib.pyplot as plt

课后习题1

1. 用高斯消元法解方程组
$$
\begin{cases}
x_1 + 2x_2 + x_3 = 0,\\
2x_1 + 2x_2 + 3x_3 = 3,\\
-\,x_1 - 3x_2 = 0.
\end{cases}
$$



In [ ]:

def gauss_elimination(matrix):
    n = len(matrix)
    # 消元过程：将增广矩阵转化为上三角矩阵
    for i in range(n-1):
        for j in range(i+1, n):
            factor = matrix[j, i] / matrix[i, i]
            matrix[j, i:] -= factor * matrix[i, i:]
    # 回代过程：求解上三角方程组
    x = np.zeros(n)
    x[-1] = matrix[-1, -1] / matrix[-1, -2]
    for i in range(n-2, -1, -1):
        x[i] = (matrix[i, -1] - np.dot(matrix[i, i+1:n], x[i+1:n])) / matrix[i, i]
    return x

# 构造问题1的增广矩阵
aug_matrix1 = np.array([
    [1, 2, 1, 0],
    [2, 2, 3, 3],
    [-1, -3, 0, 0]
], dtype=float)
x1 = gauss_elimination(aug_matrix1)
print("问题1的解：", x1)

课后习题1

2. 用列主元消元法求解方程组
$$
\begin{cases}
2x_1 + 3x_2 + 5x_3 = 5,\\
3x_1 + 4x_2 + 8x_3 = 6,\\
x_1 + 3x_2 + 3x_3 = 5.
\end{cases}
$$


In [24]:
def partial_pivot_elimination(matrix):
    n = len(matrix)
    for i in range(n-1):
        # 寻找当前列的主元行（绝对值最大）
        max_row = i
        for j in range(i, n):
            if abs(matrix[j, i]) > abs(matrix[max_row, i]):
                max_row = j
        # 交换主元行与当前行
        matrix[[i, max_row]] = matrix[[max_row, i]]
        # 消元
        for j in range(i+1, n):
            factor = matrix[j, i] / matrix[i, i]
            matrix[j, i:] -= factor * matrix[i, i:]
    # 回代求解
    x = np.zeros(n)
    x[-1] = matrix[-1, -1] / matrix[-1, -2]
    for i in range(n-2, -1, -1):
        x[i] = (matrix[i, -1] - np.dot(matrix[i, i+1:n], x[i+1:n])) / matrix[i, i]
    return x

# 构造问题2的增广矩阵
aug_matrix2 = np.array([
    [2, 3, 5, 5],
    [3, 4, 8, 6],
    [1, 3, 3, 5]
], dtype=float)
x2 = partial_pivot_elimination(aug_matrix2)
print("问题2的解：", x2)

问题2的解： [ 2.  2. -1.]


课后习题1

3. 矩阵 $A$ 的 $LU$ 分解
$$
A=\begin{pmatrix}
4 & 2 & -2\\
2 & 2 & -2\\
-2 & -3 & 13
\end{pmatrix}.
$$



In [26]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # 下三角矩阵，对角线初始化为1
    U = np.zeros((n, n))  # 上三角矩阵
    for i in range(n):
        # 计算U的第i行
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        # 计算L的第i列（i > j的情况）
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
    return L, U

# 问题3的矩阵
A3 = np.array([
    [4, 2, -2],
    [2, 2, -2],
    [-2, -3, 13]
], dtype=float)
L3, U3 = lu_decomposition(A3)
print("问题3的L矩阵：\n", L3)
print("问题3的U矩阵：\n", U3)

问题3的L矩阵：
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -2.   1. ]]
问题3的U矩阵：
 [[ 4.  2. -2.]
 [ 0.  1. -1.]
 [ 0.  0. 10.]]


课后习题1

4. 用 LU 分解法求解方程组

$$
\begin{bmatrix}
4 & 2 & -2\\
2 & 2 & -2\\
-2 & -3 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2\\ x_3
\end{bmatrix}
=
\begin{bmatrix}
8\\ 4\\ 5
\end{bmatrix}.
$$



In [28]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # 下三角矩阵，对角线初始化为1
    U = np.zeros((n, n))  # 上三角矩阵
    for i in range(n):
        # 计算U的第i行
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        # 计算L的第i列（i > j的情况）
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
    return L, U

# 问题3的矩阵
A3 = np.array([
    [4, 2, -2],
    [2, 2, -2],
    [-2, -3, 13]
], dtype=float)
L3, U3 = lu_decomposition(A3)
print("问题3的L矩阵：\n", L3)
print("问题3的U矩阵：\n", U3)

问题3的L矩阵：
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -2.   1. ]]
问题3的U矩阵：
 [[ 4.  2. -2.]
 [ 0.  1. -1.]
 [ 0.  0. 10.]]


课后习题1

5. 用 $LU$ 分解给出下列代数方程组的解及 $L$ 与 $U$ 矩阵

$$
\begin{cases}
2x_1 + 2x_2 + 3x_3 = 3,\\
4x_1 + 7x_2 + 7x_3 = 1,\\
-2x_1 + 4x_2 + 5x_3 = -7.
\end{cases}
$$


In [30]:
def lu_solve_with_lu(A, b):
    L, U = lu_decomposition(A)
    n = len(L)
    # 解Ly = b
    y = np.zeros(n)
    y[0] = b[0] / L[0, 0]
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]
    # 解Ux = y
    x = np.zeros(n)
    x[-1] = y[-1] / U[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:n], x[i+1:n])) / U[i, i]
    return x, L, U

# 问题5的矩阵A和向量b
A5 = np.array([
    [2, 2, 3],
    [4, 7, 7],
    [-2, 4, 5]
], dtype=float)
b5 = np.array([3, 1, -7], dtype=float)
x5, L5, U5 = lu_solve_with_lu(A5, b5)
print("问题5的解：", x5)
print("问题5的L矩阵：\n", L5)
print("问题5的U矩阵：\n", U5)

问题5的解： [ 2. -2.  1.]
问题5的L矩阵：
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  1.]]
问题5的U矩阵：
 [[2. 2. 3.]
 [0. 3. 1.]
 [0. 0. 6.]]
